name: Deploy Frontend Staging

on:
  push:
    branches: [ staging ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install and Build
        # Inyectamos la variable aquí para que Vite la "queme" en el JS
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          npm install
          npm run build 

      - name: Deploy to VPS via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist/*"
          # Ajustado a la ruta que definimos para Docker
          target: "~/app-discoteca/staging/front" 
          strip_components: 1